/**
 * Rett Behrens LOTR SDK
 * One API to rule them all - LibLab take home project - The Lord of the Rings SDK
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Movie {
    'id'?: string;
    'name'?: string;
    'runtimeInMinutes'?: number;
    'budgetInMillions'?: number;
    'boxOfficeRevenueInMillions'?: number;
    'academyAwardNominations'?: number;
    'academyAwardWins'?: number;
    'rottenTomatoesScore'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "runtimeInMinutes",
            "baseName": "runtimeInMinutes",
            "type": "number"
        },
        {
            "name": "budgetInMillions",
            "baseName": "budgetInMillions",
            "type": "number"
        },
        {
            "name": "boxOfficeRevenueInMillions",
            "baseName": "boxOfficeRevenueInMillions",
            "type": "number"
        },
        {
            "name": "academyAwardNominations",
            "baseName": "academyAwardNominations",
            "type": "number"
        },
        {
            "name": "academyAwardWins",
            "baseName": "academyAwardWins",
            "type": "number"
        },
        {
            "name": "rottenTomatoesScore",
            "baseName": "rottenTomatoesScore",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Movie.attributeTypeMap;
    }
}

